### ISSUE TITLE
nullValue Type Check Short Circuits Value Decode

### ISSUE THREAD

**Issue by todd** [callmehiphop/pb-util#5]
Howdy all, thanks for throwing this library together.

I'm using this library in conjunction with protobuf.js. It appears that `value.decode` short-circuits if the type of `nullValue` is not `undefined`. I'm trying to understand the correct behavior here - it appears that `nullValue` is not undefined when I deserialize a proto using protobuf.js, so it returns `null`, despite the underlying value being what I need. Here's some reproduction code.

```protobuf
syntax = "proto2";
import "google/protobuf/struct.proto";

message Diff {
  optional google.protobuf.Struct up = 1;
  optional google.protobuf.Struct down = 2;
}
```

```
> const { struct, value } = require('pb-util')
undefined
> const { Diff } = require('./myProto')
undefined
> s = struct.encode({ foo: 'foo' })
{ fields: { foo: { kind: 'stringValue', stringValue: 'foo' } } }
> diff = Diff.create({ up: s })
Diff { up: { fields: { foo: [Object] } } }
> encoded = Diff.encode(diff)
BufferWriter { ... }
> finished = encoded.finish()
<Buffer ... >
> decoded = Diff.decode(finished)
Diff { up: Struct { fields: { foo: [Value] } } }
> struct.decode(decoded.up)
{ foo: null } // <- Not right
> const { foo } = decoded.up.fields
> foo
Value { stringValue: 'foo' }
> foo.nullValue
0
> foo[foo.kind]
'foo'
```

Is this behavior expected? How can I circumvent this?

**Comment by callmehiphop** [comment]
Oh interesting, this is totally not expected. Since a field can only be a single value I wasn't really anticipating that multiple values could be present.
